apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appacuity-read-access-clusterrole
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appacuity-read-access-binding
subjects:
- kind: Group
  name: appacuity-read-access-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: appacuity-read-access-clusterrole
  apiGroup: rbac.authorization.k8s.io
